import time
import os
print()
print()
print("Welkom")
print("Please identify yourself")
identity = input("> ")
print()
print("Welcome" + identity)
time.sleep(0.5)
print()
print("Level 2 Access Clearance Granted")
print()
time.sleep(1)

print()
print("----------------------------------------------")
print("Files Object 145")
print()
print("         Interview 1")
print("         Interview 2 (Level 5 Access Required)")
print("         Interview 3 (Level 5 Access Required)")
choise = input("[1,2,3] ")
choise = choise.lower()
if choise == "1":
    print()
    print("This interview was taken when 145 wanted to join for a programing group named █████. All irrelvant infomation has been removed")
    print()
    print("Date of Recording: ██-██-2019")
    print()
    print("[BEGIN RECORD")
    print()
    print("Interviewer: Hallo, ")
    print()
    time.sleep(0.5)
    print("145: Eh ja, mijn naam is Tim")
    print()
    time.sleep(0.5)
    print("Interviewer: Dus Tim, vertel me iets over je zelf.")
    print()
    time.sleep(0.5)
    print("145: Ehm.. oke, ik ben 18 jaar, ik woon op █████ ██████ in Purmerend samen met mijn moeder, broertje en stief vader.")
    print()
    time.sleep(0.5)
    print("Interviewer: Nog iets anders?")
    print()
    time.sleep(0.5)
    print("145: Bedoel je hobby's of zo iets?")
    print()
    time.sleep(0.5)
    print("145: Ik freerun graag samen met mijn neef, eh.. ik zit op nog op judo, daar ga ik elke donderdag naar toe.")
    print()
    time.sleep(0.5)
    print("Interviewer: Zijn er nog andere dingen die ik over je zouden moeten weten?")
    print()
    time.sleep(0.5)
    print("145: Ja, ik heb autisme en tourette waardoor ik soms rare bewegingen of geluiden kan maken.")
    print()
    time.sleep(0.5)
    print("Interviewer: Oke, dat was het voor nu.")
    print()
    time.sleep(0.5)
    print("[END RECORD]")
    os.system("pause")
elif choise == "2" or choise == "3":
    print()
    print("You don't have Permision to Access this file")
    
    time.sleep(1)